#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackHome.Client.Resource", IsApplication=true)]

namespace HackHome.Client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HackHome.CustomAdapters.Resource.String.ApplicationName = global::HackHome.Client.Resource.String.ApplicationName;
			global::HackHome.CustomAdapters.Resource.String.Hello = global::HackHome.Client.Resource.String.Hello;
			global::HackHome.Entities.Resource.String.ApplicationName = global::HackHome.Client.Resource.String.ApplicationName;
			global::HackHome.Entities.Resource.String.Hello = global::HackHome.Client.Resource.String.Hello;
			global::HackHome.SAL.Resource.Animation.slide_in_right = global::HackHome.Client.Resource.Animation.slide_in_right;
			global::HackHome.SAL.Resource.Animation.slide_out_left = global::HackHome.Client.Resource.Animation.slide_out_left;
			global::HackHome.SAL.Resource.Drawable.ic_arrow_back = global::HackHome.Client.Resource.Drawable.ic_arrow_back;
			global::HackHome.SAL.Resource.Id.webview = global::HackHome.Client.Resource.Id.webview;
			global::HackHome.SAL.Resource.Layout.activity_webview = global::HackHome.Client.Resource.Layout.activity_webview;
			global::HackHome.SAL.Resource.String.ApplicationName = global::HackHome.Client.Resource.String.ApplicationName;
			global::HackHome.SAL.Resource.String.Hello = global::HackHome.Client.Resource.String.Hello;
			global::HackHome.SAL.Resource.String.title_activity_webview = global::HackHome.Client.Resource.String.title_activity_webview;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int land = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int port = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int emailEditText = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int emailTextView = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int evidenceDescription = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int evidenceImageView = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int evidenceListView = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int evidenceStatusTextView = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int evidenceTextView = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int evidenceTitleTextView = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int fullNameTextView = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout2 = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int orientationImage = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int passwordEditText = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int passwordTextView = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int validateButton = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Evidence = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EvidenceDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EvidenceItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int Description = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int Error_Authentication = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Evidence = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int InvalidUserOrNotInEvent_Authentication = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int OutOfDate_Authentication = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Validate = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
